// layout.tsx (sin la directiva "use client")
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Nabvar";
import Footer from "@/components/Footer";
import ButtonFloating from "@/components/ButtonFloating";
import { AuthProvider } from "../../hooks/useAuth";
import { AuthProvider as AuthProviderAdmin } from "../../hooks/useAuthAdmin";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// La metadata debe estar fuera de la directiva "use client"
export const metadata: Metadata = {
  title: "UDEA | Biblioteca virtual",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <AuthProviderAdmin>
            <Navbar />
            {children}
            <ButtonFloating />
            <Footer />
          </AuthProviderAdmin>
        </AuthProvider>
      </body>
    </html>
  );
}
